-   id: ktlint
    name: ktlint
    description: Runs ktlint
    entry: ./gradlew ktlint
    pass_filenames: false
    language: system

-   id: detekt
    name: detekt
    description: Runs detekt
    entry: ./gradlew detekt
    pass_filenames: false
    language: system

-   id: unit_tests
    name: unittests
    description: Runs unit tests
    entry: ./gradlew testDebugUnitTest
    pass_filenames: false
    language: system

-   id: build
    name: build
    description: Building App
    entry: ./gradlew assembleDebug
    pass_filenames: false
    language: system
